<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail [
  <!ELEMENT mail (to, from, subject, message)>
  <!ELEMENT to (#PCDATA)>
  <!ELEMENT from (#PCDATA)>
  <!ELEMENT subject (#PCDATA)>
  <!ELEMENT message (#PCDATA)>
]>
<mail>
  <to>example@example.com</to>
  <from>sender@example.com</from>
  <subject>Test Mail</subject>
  <message>This is a test message.</message>
</mail>

<!-- 2075 internal dtd -->